[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps --no-audit --no-fund && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --no-audit --no-fund"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
