name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      env:
        FORK_ENABLED: 'true'
        BASE_MAINNET_RPC_URL: ${{ secrets.BASE_MAINNET_RPC_URL }}
      run: |
        if [ -z "${{ secrets.BASE_MAINNET_RPC_URL }}" ]; then
          echo "Error: BASE_MAINNET_RPC_URL secret is not set"
          exit 1
        fi
        npx hardhat test
