name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: |
          if [ ! -f "package-lock.json" ]; then
            echo "No package-lock.json found, running npm install..."
            npm install
          else
            echo "Using existing package-lock.json..."
            npm ci
          fi

      - name: Verify BASE_MAINNET_RPC_URL
        run: |
          if [ -z "${{ secrets.BASE_MAINNET_RPC_URL }}" ]; then
            echo "Error: BASE_MAINNET_RPC_URL secret is not set"
            exit 1
          fi

      - name: Run tests
        env:
          FORK_ENABLED: "true"
          BASE_MAINNET_RPC_URL: ${{ secrets.BASE_MAINNET_RPC_URL }}
          FORK_BLOCK_NUMBER: "12300000"
        run: npm test
